name: cts_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - jupyterlab
  - ipykernel
  - numpy=2.0.*
  - pandas=2.2.*
  - matplotlib=3.10.*
  - rasterio=1.5.*
  - pyproj=3.7.*
  - tqdm=4.67.*
  - matplotlib-scalebar
  - pip
  - pip:
      - matplotlib-map-utils
